
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Service\LoggerService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Mailer\FileTransport:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Mailer\MailerService:
        public: true

    App\Interface\MailerTransportInterface: '@App\Service\Mailer\NullTransport'
